name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        # Insert commands to build your project here
        # For example, if you're using Node.js:
        npm install
        npm run build

    - name: Test
      run: |
        # Insert commands to run tests here
        # For example, if you're using Node.js:
        # npm run test

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dionydion/auth-client:latest

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: 13.211.188.192
        username: ${{ secrets.EC2_USERNAME }}
        password: ${{ secrets.EC2_PASSWORD }}
        port: 22
        script: |
          # Insert commands to pull and run Docker image here
          docker pull dionydion/auth-client:latest
          docker run -d -p 3000:3000 dionydion/auth-client:latest
