name: Build, Test, and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Insert commands to build your project here
          # For example, if you're using Node.js:
          npm install
          npm run build

      - name: Test
        run: |
          # Insert commands to run tests here
          # For example, if you're using Node.js:
          # npm run tes

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dionydion/auth-client:latest

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 13.211.188.192
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker stop $(sudo docker ps -a -q -f "ancestor=dionydion/auth-client:latest") || true && sudo docker rm $(sudo docker ps -a -q -f "ancestor=dionydion/auth-client:latest") || true
            sudo docker pull dionydion/auth-client:latest
            sudo docker run -p -d 3000:3000 dionydion/auth-client:latest

      # - name: Stop and remove existing container
      #   run: |
      #     sudo docker stop $(sudo docker ps -a -q -f "ancestor=dionydion/auth-client:latest") || true && sudo docker rm $(sudo docker ps -a -q -f "ancestor=dionydion/auth-client:latest") || true
      #   # run: |
      #   # IMAGE_NAME=<dionydion/auth-client:latest>
      #   # CONTAINER_IDS=$(sudo docker ps -q -f ancestor=$IMAGE_NAME)
      #   # if [ -n "$CONTAINER_IDS" ]; then
      #   #   sudo docker stop $CONTAINER_IDS
      #   #   sudo docker rm $CONTAINER_IDS
      #   # fi
      #   # #

      # - name: Pull updated Docker image
      #   run: |
      #     sudo docker pull dionydion/auth-client:latest

      # - name: Start new container
      #   run: |
      #     sudo docker run -p 3000:3000 dionydion/auth-client:latest
